module.exports = {
  printWidth: 150,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  vueIndentScriptAndStyle: false,
  singleQuote: false,
  quoteProps: "as-needed",
  bracketSameLine: true,
  bracketSpacing: true,
  trailingComma: "none",
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  arrowParens: "always",
  insertPragma: false,
  requirePragma: false,
  proseWrap: "never",
  htmlWhitespaceSensitivity: "strict",
  endOfLine: "auto",
  rangeStart: 0
};
